spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

debug: true

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    # exception-handlers-enabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
#  cdn:
#    enabled: false
#    version: 0.13.0
#  props:
#    resources:
#      query: query.graphql
#      defaultQuery: defaultQuery.graphql
#      variables: variables.graphql
#    variables:
#      editorTheme: "solarized light"
#  headers:
#    Authorization: "Bearer <your-token>"